/**
 * Ascendant (Lagna) personality profiles — based on classical Vedic texts
 */
export const ASCENDANT_TEXTS = {
  1: { // Aries
    sign: 'Aries', title: 'Mesha Lagna',
    personality: 'You are bold, pioneering, and fiercely independent. A natural leader with abundant energy, you charge headfirst into challenges. Your enthusiasm is infectious, though patience is not your strongest virtue. You possess a sharp intellect and quick decision-making ability.',
    appearance: 'Medium to tall stature with a strong, athletic build. Your face is typically oval-shaped with a prominent forehead. You have piercing eyes and a confident gait.',
    nature: 'Courageous, ambitious, and determined. You are a self-starter who thrives on competition. Sometimes impulsive, you prefer action over prolonged deliberation. Generous with friends but can be argumentative when provoked.',
    career: 'You excel in leadership roles, entrepreneurship, military, sports, surgery, engineering, and any field requiring initiative and courage. You are a natural trailblazer in your profession.',
    health: 'Generally robust constitution. Prone to headaches, fevers, inflammatory conditions, and injuries to the head region. Regular physical activity is essential for your well-being.',
    relationships: 'Passionate and devoted in love. You seek a partner who matches your energy and independence. You are protective of family and can be dominating in relationships. Early marriage is common.',
  },
  2: { // Taurus
    sign: 'Taurus', title: 'Vrishabha Lagna',
    personality: 'You are practical, reliable, and deeply grounded. Blessed with remarkable patience and determination, you build your life on solid foundations. You have a keen appreciation for beauty, art, and the finer things in life.',
    appearance: 'Well-built and sturdy frame with a tendency toward fullness. Attractive face with large, expressive eyes. Pleasant voice and a calm, composed demeanor.',
    nature: 'Steady, loyal, and enduring. You value stability and security above all. Slow to anger but formidable when provoked. You are sensual and enjoy material comforts. Conservative in approach but generous in nature.',
    career: 'Success in finance, banking, agriculture, real estate, hospitality, arts, music, and luxury goods. You build wealth steadily and are excellent at managing resources.',
    health: 'Strong constitution with good stamina. Susceptible to throat ailments, thyroid issues, and weight gain. Overindulgence in food and comfort can affect health. Moderate lifestyle brings longevity.',
    relationships: 'Deeply loyal and devoted partner. You seek lasting, stable relationships. Very affectionate and nurturing. Possessiveness can sometimes create tension. You create a comfortable and beautiful home.',
  },
  3: { // Gemini
    sign: 'Gemini', title: 'Mithuna Lagna',
    personality: 'You are intellectually curious, versatile, and exceptionally communicative. Your mind is quick and agile, always seeking new information and experiences. You possess a natural charm and wit that draws people to you.',
    appearance: 'Slender and tall with an expressive face. Bright, curious eyes and animated gestures. You appear younger than your age and have a lively, energetic presence.',
    nature: 'Adaptable, witty, and sociable. You thrive on mental stimulation and variety. Can be restless and prone to changing interests. Excellent at multitasking. You see both sides of every situation.',
    career: 'Natural talent for communication, writing, journalism, teaching, sales, trading, technology, and media. You may pursue multiple careers simultaneously or change fields several times.',
    health: 'Nervous energy can lead to anxiety and respiratory issues. Prone to problems with arms, shoulders, and lungs. Mental rest and breathing exercises are particularly beneficial for you.',
    relationships: 'You need a partner who can match your intellectual depth. Flirtatious and playful in romance. Communication is the key to your relationships. You may marry more than once or marry late.',
  },
  4: { // Cancer
    sign: 'Cancer', title: 'Karka Lagna',
    personality: 'You are deeply intuitive, emotionally rich, and profoundly nurturing. Your sensitivity to others\' feelings makes you an exceptional caretaker. You have a powerful imagination and strong connection to home and family.',
    appearance: 'Round or oval face with soft features. Medium height with a tendency to retain water. Expressive, dreamy eyes. Your appearance changes with your mood.',
    nature: 'Caring, protective, and sentimental. You are deeply attached to home, family, and traditions. Mood swings are common. You have excellent memory and strong psychic abilities. Tenacious when pursuing goals.',
    career: 'Excellence in hospitality, nursing, cooking, real estate, interior design, psychology, social work, and marine activities. You also do well in businesses from home.',
    health: 'Sensitive digestive system. Prone to stomach disorders, chest problems, and water retention. Emotional stress directly affects physical health. A stable emotional environment promotes healing.',
    relationships: 'Deeply loving and devoted. You create a warm, nurturing home environment. Tend to be clingy or overprotective. Your partner must understand your emotional depths. Strong bond with mother.',
  },
  5: { // Leo
    sign: 'Leo', title: 'Simha Lagna',
    personality: 'You are majestic, confident, and born to lead. With a natural sense of authority and charisma, you command attention wherever you go. Generous and warm-hearted, you have a flair for the dramatic.',
    appearance: 'Strong, impressive physique with a broad chest. Mane-like hair and commanding presence. Regal bearing with a warm, radiant smile. You carry yourself with dignity.',
    nature: 'Proud, generous, and creative. You have a strong sense of honor and cannot tolerate disrespect. Natural organizer and leader. You are magnanimous to those you love but can be domineering.',
    career: 'Government service, politics, entertainment, performing arts, management, and any position of authority. You thrive as a CEO, director, or administrator. Creative fields also favor you.',
    health: 'Generally strong vitality. Prone to heart conditions, back problems, and eye strain. Stress from excessive responsibility can take its toll. Regular relaxation and heart care are essential.',
    relationships: 'Passionate and dramatic in love. You need admiration and loyalty from your partner. Generous and protective, you shower your loved ones with gifts. Ego clashes can arise if not managed.',
  },
  6: { // Virgo
    sign: 'Virgo', title: 'Kanya Lagna',
    personality: 'You are analytical, meticulous, and service-oriented. Blessed with a keen eye for detail, you excel at organizing and perfecting everything you touch. Your practical wisdom and discriminating intellect are your greatest assets.',
    appearance: 'Medium height with a neat, well-proportioned body. Intelligent eyes with a thoughtful expression. You maintain a clean, organized appearance. Youthful looks that age gracefully.',
    nature: 'Practical, modest, and hardworking. You are a perfectionist who sets high standards. Helpful and service-minded. Can be critical and worry-prone. You prefer method and order in all things.',
    career: 'Healthcare, accounting, editing, research, quality control, nutrition, veterinary science, and any work requiring precision. You excel in analytical and service-oriented roles.',
    health: 'Digestive sensitivity is common. Prone to intestinal issues, skin allergies, and nervous disorders. Worry and anxiety can aggravate conditions. A regulated diet and stress management are crucial.',
    relationships: 'Devoted and attentive partner. You show love through acts of service. Can be overly critical of partners. You need intellectual compatibility. Slow to commit but deeply faithful once dedicated.',
  },
  7: { // Libra
    sign: 'Libra', title: 'Tula Lagna',
    personality: 'You are graceful, diplomatic, and deeply drawn to harmony and beauty. With an innate sense of justice and fairness, you excel at bringing balance to any situation. Your charm and social skills make you universally liked.',
    appearance: 'Well-proportioned, attractive figure. Symmetrical features with a pleasant, winning smile. Graceful movements and an eye for fashion. You have a natural elegance.',
    nature: 'Balanced, charming, and cooperative. You abhor conflict and seek harmony in all relationships. Artistic and aesthetically inclined. Can be indecisive. You weigh all options carefully before deciding.',
    career: 'Law, diplomacy, fashion, interior design, counseling, art, music, and public relations. You excel in partnerships and collaborative ventures. Judicial and advisory roles suit you.',
    health: 'Kidneys and lower back are vulnerable. Prone to urinary problems, diabetes, and skin conditions. Stress from relationship conflicts affects health. Balance in diet and lifestyle is key.',
    relationships: 'Partnership-oriented — you feel complete in relationships. Romantic and attentive lover. You need intellectual and aesthetic compatibility. Marriage is very important to you. You create beautiful shared spaces.',
  },
  8: { // Scorpio
    sign: 'Scorpio', title: 'Vrishchika Lagna',
    personality: 'You are intense, powerful, and profoundly perceptive. With unmatched determination and willpower, you delve deep into life\'s mysteries. You possess tremendous regenerative power and transformative energy.',
    appearance: 'Magnetic, penetrating eyes that seem to see through people. Medium build with a strong, compact frame. Intense facial expressions. Your presence is felt before you speak.',
    nature: 'Passionate, resourceful, and secretive. You operate with total commitment in everything. Fiercely loyal to those you trust. You never forget a betrayal. Tremendous capacity for self-transformation.',
    career: 'Research, investigation, medicine, surgery, psychology, occult sciences, mining, and insurance. You excel in uncovering hidden truths. Forensics and detective work suit you.',
    health: 'Reproductive organs and excretory system need attention. Prone to infections, fevers, and surgical interventions. Strong recovery powers. Regular detoxification and emotional release are beneficial.',
    relationships: 'All-or-nothing approach to love. Intensely passionate and jealous. Deep emotional bonds. You need complete trust and honesty. Can be possessive but extraordinarily devoted. Transformative relationships.',
  },
  9: { // Sagittarius
    sign: 'Sagittarius', title: 'Dhanu Lagna',
    personality: 'You are optimistic, philosophical, and freedom-loving. A natural explorer, you seek meaning and truth in all experiences. Your enthusiasm and broad vision inspire everyone around you.',
    appearance: 'Tall, well-built frame. Open, friendly face with an expressive forehead. Athletic build. Your eyes sparkle with optimism. You carry yourself with confidence and openness.',
    nature: 'Generous, honest, and adventurous. You value freedom and truth above all. Natural teacher and philosopher. Can be blunt and tactless. You have strong moral convictions and religious inclinations.',
    career: 'Teaching, law, philosophy, publishing, travel industry, sports, and religious leadership. You thrive in roles that expand knowledge and horizons. International work suits you.',
    health: 'Hips, thighs, and liver are sensitive areas. Prone to weight gain, sciatica, and liver problems. Active lifestyle is essential. Outdoor activities and sports keep you in excellent shape.',
    relationships: 'Freedom-loving in relationships. You need a partner who shares your love for adventure and growth. Honest and straightforward. May marry a person from different culture. Loyal but need space.',
  },
  10: { // Capricorn
    sign: 'Capricorn', title: 'Makara Lagna',
    personality: 'You are disciplined, ambitious, and profoundly responsible. With unwavering determination, you climb steadily toward your goals. You possess a mature outlook from an early age and value tradition and structure.',
    appearance: 'Lean, angular frame that becomes more distinguished with age. Prominent bone structure. Serious expression that softens with familiarity. You improve in appearance as you mature.',
    nature: 'Practical, cautious, and persistent. You take a long-term view of everything. Conservative and traditional. Can appear cold but have deep feelings. Excellent organizational and managerial abilities.',
    career: 'Government, administration, construction, mining, agriculture, and corporate leadership. You rise steadily to positions of authority. Real estate and traditional businesses favor you.',
    health: 'Bones, joints, and knees require attention. Prone to arthritis, dental issues, and skin dryness. Health improves with age. Calcium-rich diet and regular exercise maintain structural health.',
    relationships: 'Slow to open up but deeply committed once in love. You seek a partner who respects tradition and stability. Marriage improves with time. You are a responsible and providing partner.',
  },
  11: { // Aquarius
    sign: 'Aquarius', title: 'Kumbha Lagna',
    personality: 'You are innovative, humanitarian, and deeply independent in thought. A visionary who thinks ahead of your time, you are drawn to social causes and progressive ideas. Your intellectual approach to life sets you apart.',
    appearance: 'Tall, well-formed body. Distinctive, often unconventional appearance. Bright, intelligent eyes. You may favor unique or eccentric styles. Friendly, approachable demeanor.',
    nature: 'Intellectual, detached, and humanitarian. You value friendship highly and maintain a wide social circle. Can appear emotionally distant. You are unpredictable and original. Strong sense of social justice.',
    career: 'Technology, science, social work, NGOs, aviation, astrology, and innovation-driven fields. You excel in group projects and organizations working for social change.',
    health: 'Circulation and ankles are vulnerable. Prone to varicose veins, nervous disorders, and unusual ailments. Irregular habits can affect health. Adequate sleep and grounding activities help.',
    relationships: 'You value friendship in love — your partner must be your best friend first. Need intellectual freedom in relationships. Unconventional approach to romance. Loyal but need independence.',
  },
  12: { // Pisces
    sign: 'Pisces', title: 'Meena Lagna',
    personality: 'You are compassionate, intuitive, and deeply spiritual. With an extraordinary sensitivity to the unseen world, you possess artistic gifts and healing abilities. Your empathy knows no bounds.',
    appearance: 'Soft, dreamy features with large, soulful eyes. Medium build with a tendency toward softness. Gentle expression. You have a calming, almost ethereal presence.',
    nature: 'Compassionate, imaginative, and self-sacrificing. You absorb the emotions of those around you. Highly creative and artistic. Can be escapist and impractical. Deep spiritual and mystical inclinations.',
    career: 'Arts, music, film, spiritual healing, charity work, marine biology, hospitals, and monasteries. You excel in roles that require compassion, creativity, and spiritual connection.',
    health: 'Feet and lymphatic system need care. Prone to allergies, addictions, and psychosomatic illnesses. Emotional boundaries are essential. Water therapy, meditation, and adequate rest support health.',
    relationships: 'Deeply romantic and self-sacrificing. You idealize love and can be disappointed by reality. Need a grounded partner. Soulmate connections are important. You give everything in love.',
  },
};
