/**
 * Mahadasha Phal — Predictions for each planet's Mahadasha based on house placement
 * Based on Brihat Parashara Hora Shastra & Phaladeepika
 */

const H = {
  1: 'ascendant', 2: 'wealth/family', 3: 'courage/siblings', 4: 'home/mother',
  5: 'children/education', 6: 'enemies/health', 7: 'marriage/partnerships',
  8: 'longevity/obstacles', 9: 'fortune/dharma', 10: 'career/karma',
  11: 'gains/income', 12: 'expenses/liberation',
};

function dp(planet, house, text) { return text; }

export const DASHA_PHAL = {
  SUN: {
    1: 'This is a good time for self-expression and leadership. You will gain recognition, confidence, and authority. Government favor is likely. Health and vitality improve. You may take on important responsibilities and gain respect in society.',
    2: 'Family matters come into focus. There may be gains through government or authority figures. Speech becomes powerful and influential. However, there could be some eye-related issues. Accumulation of wealth through own efforts is indicated.',
    3: 'Courage and initiative increase dramatically. Success through bold actions and short travels. Relationship with siblings improves. Communications become more authoritative. You may take up writing or media-related activities.',
    4: 'Mixed period for domestic happiness. You may acquire property or vehicles. Relationship with mother needs attention. Government may provide housing or land benefits. There could be changes in residence or renovation of home.',
    5: 'Excellent period for education, creativity, and children. Speculative gains are possible. Romance flourishes. Your intelligence is recognized. You may receive awards or academic honors. Children bring joy and pride.',
    6: 'Victory over enemies and competitors. Health generally improves but watch for fevers and inflammatory conditions. Legal matters resolve in your favor. You overcome obstacles through courage. Service and employment bring recognition.',
    7: 'Partnership matters are highlighted. Marriage or business partnerships may undergo changes. Travel for business purposes. Your public image strengthens. Spouse may gain authority. Some ego clashes in relationships are possible.',
    8: 'A challenging period requiring caution. Health of father or authority figures needs attention. There may be obstacles in career. Hidden matters come to light. Transformation through difficulties. Government opposition is possible.',
    9: 'Favorable for spiritual growth, higher education, and long-distance travel. Father\'s influence is positive. Religious pilgrimages bring peace. Fortune improves through righteous actions. Teaching and mentoring others bring satisfaction.',
    10: 'The most unexpected positive changes in your career. Favor from higher authorities and seniors. Professional success and public recognition. You may receive a significant promotion or start an important venture. Government connections strengthen.',
    11: 'Excellent period for income and gains. Friendships with influential people bring opportunities. Wishes and aspirations are fulfilled. Social circle expands. Elder siblings prosper. Multiple sources of income develop.',
    12: 'Increased expenses and possible foreign travel. Spiritual inclinations grow stronger. You may face government-related expenses or fines. Rest and retreat are necessary. Hospital visits possible. Donations to charitable causes bring inner peace.',
  },
  MOON: {
    1: 'Emotional well-being improves. Public popularity and recognition increase. You become more nurturing and caring. Travel and changes of environment are likely. Mental peace and creativity flourish. New beginnings in personal life.',
    2: 'Family prosperity and harmony. Financial gains through food, dairy, or hospitality industries. Voice and speech improve. Accumulation of precious items. Family gatherings bring joy. Silver and pearls may come into your possession.',
    3: 'Increased courage and communication skills. Creative writing abilities shine. Short travels bring pleasure and profit. Relationship with siblings and neighbors improves. Media and artistic activities flourish.',
    4: 'Excellent for domestic happiness, property acquisition, and relationship with mother. You may purchase a home or vehicle. Emotional security improves. Educational pursuits at home bear fruit. Inner contentment grows.',
    5: 'Romance, children, and creativity are beautifully highlighted. Love relationships deepen. Children bring happiness. Creative projects succeed. Intelligence and intuition combine for excellent results. Speculative gains possible.',
    6: 'Health needs attention — especially digestive system and emotional well-being. Victory over competitors through patience. Service to others brings recognition. Maternal health may need monitoring. Debts get resolved gradually.',
    7: 'Marriage and partnerships flourish. A beautiful period for romance and companionship. Business partnerships bring gains. Travel with spouse or partner. Public relations improve. Social life becomes active and rewarding.',
    8: 'There may be some bad news regarding business or ventures. Family members\' health may cause anxiety. Avoid speculation as it may cause financial losses. Opponents will try to create problems. Stay cautious near water. Some health issues with cold and fever.',
    9: 'Spiritual growth and long-distance travel. Connection with mother deepens. Religious observances bring peace. Fortune favors through intuition and compassion. Pilgrimages to water bodies are especially beneficial.',
    10: 'Career advancement through public popularity. You gain recognition for your nurturing leadership style. Government positions may open up. Public-facing roles bring success. You become known for compassion and care in professional settings.',
    11: 'Gains from friendships and social connections. Wishes manifest through emotional intelligence. Income increases through public-facing ventures. Social gatherings bring opportunities. Aspirations related to home and family are fulfilled.',
    12: 'Foreign travel and spiritual retreat are indicated. Expenses on comforts and pleasures increase. Dreams become vivid and prophetic. Connection with spiritual mother figures. Charitable activities bring deep satisfaction.',
  },
  MARS: {
    1: 'Tremendous energy, courage, and initiative. You become a force of nature. Physical fitness improves. Leadership opportunities arise. However, control anger and impulsiveness. Competitive situations favor you.',
    2: 'Income through technical or martial fields. Family discussions become heated. Dental or facial procedures possible. Accumulation of property and metals. Speech becomes direct and forceful.',
    3: 'Exceptional courage and determination. Success through bold communication. Victory over competitors. Short travels bring gains. Siblings may need your support. Excellent for athletes and military personnel.',
    4: 'Property acquisition through effort. Home renovations or construction activities. Mother\'s health needs attention. May purchase land or vehicle. Some domestic disagreements possible. Real estate investments favor you.',
    5: 'Energy directed toward children and creative projects. Sports and competitions bring accolades. Romance is passionate but intense. Speculative gains through calculated risks. Education in technical fields excels.',
    6: 'Powerful victory over enemies and disease. Health issues are overcome with vigor. Legal battles resolve in your favor. Service in competitive environments brings recognition. Military and police careers advance strongly.',
    7: 'Marriage and partnerships require patience. Spouse becomes more assertive. Business partnerships may face friction. Travel increases. Passionate but argumentative relationship dynamics. Learning to compromise is key.',
    8: 'Transformation through challenge. Surgical procedures may be necessary. Insurance or inheritance matters arise. Hidden enemies are exposed. Research into occult or deep subjects brings breakthroughs. Careful driving is advised.',
    9: 'Adventurous long-distance travel. Interest in martial philosophies and dharmic action. Father\'s influence is strong. Fortune through bold actions. Religious debates and philosophical arguments. Physical pilgrimages undertaken.',
    10: 'Success in examinations, promotions, and professional recognition. Increased cooperation from the family. Help from people in faraway places. You may get a new assignment which will be very beneficial. Tremendous confidence to handle adverse situations.',
    11: 'Excellent gains through technical skills and competitive abilities. Friendships with military or sports figures. Income from property and real estate. Elder siblings prosper. Ambitious goals are achieved through effort.',
    12: 'Expenses on property, surgery, or foreign travel. Sleep disturbances possible. Meditation and martial arts balance your energy. Charitable activities involving physical service bring satisfaction. Hospital visits for self or others.',
  },
  MERCURY: {
    1: 'Intellectual abilities shine. Communication skills improve dramatically. Business acumen sharpens. You appear more youthful and clever. Learning new skills comes easily. Writing and speaking engagements increase.',
    2: 'Financial gains through intelligence and communication. Business profits increase. Speech becomes eloquent and persuasive. Family education improves. Accumulation through smart investments and trading.',
    3: 'Brilliant period for communication, writing, and media. Short business trips bring profits. Siblings flourish. Contracts and agreements favor you. Technology and digital ventures succeed.',
    4: 'Educational pursuits at home flourish. Property documentation and legal matters resolve. Intellectual home environment. Mother\'s advice proves valuable. Real estate transactions through clever negotiation.',
    5: 'Excellent for education and intellectual creativity. Children excel academically. Speculative gains through analysis. Romance through intellectual connections. Writing and publishing achievements.',
    6: 'Victory over competitors through intelligence. Health issues related to nerves or skin are resolved. Legal matters favor you through documentation. Service through intellectual abilities. Analytical skills overcome obstacles.',
    7: 'Business partnerships thrive through clear communication. Marriage benefits from intellectual exchange. Contracts and legal agreements favor partnerships. Travel for business is profitable.',
    8: 'Research and investigation bring breakthroughs. Interest in occult mathematics or hidden knowledge. Insurance and tax matters need attention. Health checkups for nervous system recommended.',
    9: 'Higher education and philosophical studies flourish. Travel for learning brings wisdom. Writing and publishing achieve recognition. Fortune through intellect and communication. Teaching opportunities arise.',
    10: 'Career advancement through intellectual abilities. Promotions through demonstrated competence. Business communications bring new contracts. Professional education and certifications open doors.',
    11: 'Increase of income and bank balances. New ventures bring good results. New friendships and relationships through intellectual circles. Cherished desires are fulfilled. New trade or contracts materialize. Help from influential people. Overall prosperity is indicated.',
    12: 'Expenses on education and communication. Foreign education opportunities. Writing in solitude produces excellent work. Research in quiet environments. Dreams may contain important messages.',
  },
  JUPITER: {
    1: 'Wisdom, optimism, and spiritual growth define this period. You gain weight — both physically and in social stature. Teachers and mentors appear. Religious activities increase. Your counsel is sought by many.',
    2: 'Wealth accumulation through teaching, advisory, or religious work. Family expands and prospers. Speech becomes wise and measured. Valuable collections grow. Food and celebrations increase.',
    3: 'Philosophical communications and religious writings. Teaching younger people brings fulfillment. Siblings benefit from your guidance. Publishing and media work related to wisdom traditions succeeds.',
    4: 'Excellent for domestic happiness and property. Mother\'s blessings bring fortune. Home becomes a center of learning. Property investments bring long-term gains. Vehicles and comforts increase.',
    5: 'Superb period for children, education, and creative wisdom. Children achieve excellence. Romantic connections with spiritual depth. Creative projects with philosophical content succeed. Awards and recognition for intelligence.',
    6: 'Enemies are defeated through righteousness. Health improves through proper diet and positive attitude. Legal matters resolve through wise counsel. Service to the less fortunate brings blessings.',
    7: 'Partnerships are blessed with wisdom and growth. Marriage deepens. Business partnerships with wise individuals prosper. International collaborations succeed. Spouse brings fortune and wisdom.',
    8: 'Spiritual transformation and mystical experiences. Inheritance or unexpected wealth. Interest in longevity practices and ancient wisdom. Research into hidden knowledge brings insights. Protection from serious harm.',
    9: 'The most fortunate placement for Jupiter\'s Mahadasha. Spiritual pilgrimages, higher education, and dharmic activities flourish. Father\'s blessings strengthen. Fortune expands in all directions. Teaching and mentoring at highest levels.',
    10: 'Partnerships are good for you, in both professional and personal spheres. You might have an overwhelming, life-changing experience. You maintain closeness with parents, siblings and relatives. Communications bring new opportunities. Travel regarding business. You may purchase precious metals, gems and jewelry.',
    11: 'Maximum gains and income expansion. Wishes are fulfilled beyond expectations. Friendships with wise and wealthy individuals. Social status rises. Elder siblings prosper. All aspirations are achievable.',
    12: 'Spiritual liberation and foreign connections. Charitable donations bring immense merit. Foreign travel for religious purposes. Expenses on worthy causes. Retreat and meditation bring profound peace.',
  },
  VENUS: {
    1: 'Beauty, charm, and artistic abilities bloom. Love and romance enter your life. Physical appearance improves. Social popularity soars. Creative talents are recognized. A beautiful period for self-expression.',
    2: 'Wealth through art, beauty, or luxury industries. Family harmony increases. Voice becomes melodious. Precious jewelry and beautiful possessions accumulate. Gourmet food and fine dining bring pleasure.',
    3: 'Creative communications and artistic endeavors. Musical or artistic achievements. Siblings share in your joy. Short pleasure trips bring romance. Media work related to arts and entertainment succeeds.',
    4: 'Home becomes beautiful and luxurious. Vehicles and comforts increase. Mother\'s love brings happiness. Property in scenic locations. Interior decoration and home improvement activities. Domestic bliss.',
    5: 'Romance flourishes magnificently. Children bring artistic pride. Creative projects achieve spectacular success. Love affairs are passionate and beautiful. Speculative gains through beauty and entertainment industries.',
    6: 'Overcoming obstacles through charm and diplomacy. Health through beauty treatments. Competitors are charmed rather than conquered. Service in artistic capacities. Pets and animals bring joy.',
    7: 'Outstanding period for marriage and partnerships. Love marriage is possible. Business partnerships with creative people prosper. Foreign spouse or partner possible. Social life becomes glamorous.',
    8: 'Transformation through love and beauty. Inheritance of jewelry or art. Interest in tantric or mystical arts. Deep intimate connections. Insurance matters related to valuables.',
    9: 'Fortune through art, culture, and international connections. Travel to beautiful places. Spiritual experiences through beauty and love. Cultural education and appreciation of world arts.',
    10: 'Career in arts, fashion, or beauty industries flourishes. Professional recognition for aesthetic abilities. Business success through charm and diplomacy. Public image becomes glamorous.',
    11: 'Gains through social connections and artistic networks. Wishes related to love and beauty are fulfilled. Friendships with artists and beautiful people. Income through creative enterprises.',
    12: 'Spending on luxuries and comforts but put a check on it. Disappointments in love affairs and family troubles are possible. Rivals will try to harm you so be cautious in personal and professional matters. Family health concerns. Financially not bad but control expenses. Take care of your health.',
  },
  SATURN: {
    1: 'A period of discipline, maturity, and hard work. You take on serious responsibilities. Life becomes more structured. Health needs attention — especially bones and joints. You gain wisdom through patience and perseverance.',
    2: 'Family responsibilities increase. Financial conservation is wise. Speech becomes measured and serious. Dental and throat issues possible. Slow but steady wealth accumulation through traditional means.',
    3: 'Courage through endurance. Communication becomes serious and authoritative. Siblings may face challenges. Technical writing and research succeed. Short travels for work purposes.',
    4: 'Property matters require patience. Mother\'s health may need attention. Home may feel restrictive. Old property repairs or renovations. Connection with ancestral land. Gradual improvement in domestic life.',
    5: 'Education requires extra effort but produces lasting results. Romance is serious and committed. Children face challenges but build character. Creative projects require discipline but yield permanent results.',
    6: 'Excellent for overcoming long-standing enemies and chronic health issues. Legal matters resolve through persistence. Service and labor bring gradual recognition. Discipline overcomes all obstacles.',
    7: 'Marriage is tested but strengthened through commitment. Business partnerships require patience. Spouse may face health issues. Joint ventures with older or experienced people succeed.',
    8: 'Longevity and transformation through endurance. Chronic health matters surface for resolution. Research into deep subjects brings insights. Inheritance delayed but eventually received. Spiritual maturation.',
    9: 'This period can be called a dawn of a good period. You are likely to be involved in charitable and religious deeds. Foreign travel for work or spiritual purposes. Father\'s health needs care. Slow but certain spiritual growth through discipline.',
    10: 'Career reaches a pinnacle through sustained effort. Authority positions are achieved. Government service and administrative roles bring recognition. Hard work over years finally pays off substantially.',
    11: 'Gains through perseverance and long-term relationships. Old friendships prove valuable. Income stabilizes and grows. Wishes manifest slowly but permanently. Recognition from elder statesmen and organizations.',
    12: 'Spiritual detachment and introspection. Expenses on health or foreign travel. Solitude brings wisdom. Past karma is resolved. Charitable service in difficult environments. Liberation through discipline.',
  },
  RAHU: {
    1: 'Sudden changes in personality and direction. Unconventional opportunities arise. Foreign connections strengthen. Ambition reaches new heights. Health needs monitoring — unusual ailments possible. Innovation and risk-taking define this period.',
    2: 'Unexpected wealth through unconventional sources. Foreign food or business brings income. Family dynamics shift. Speech becomes impactful but sometimes controversial. Accumulation through technology or foreign trade.',
    3: 'Bold communications and unconventional media success. Technology-driven ventures prosper. Siblings involved in unusual activities. Travels to foreign or unusual places. Breakthrough in digital or social media.',
    4: 'Unconventional property or foreign real estate. Mother\'s life may undergo changes. Home environment shifts dramatically. Technology in the home increases. Unexpected domestic developments.',
    5: 'Unconventional romance or creative pursuits. Children may show unusual talents. Speculative gains through technology. Interest in foreign education. Dramatic and unexpected creative breakthroughs.',
    6: 'Victory over hidden enemies. Unusual health symptoms require specialized treatment. Legal matters involving foreigners or technology. Service through unconventional means. Overcoming obstacles through innovation.',
    7: 'Foreign or unconventional partnerships. Marriage may involve cross-cultural elements. Business with foreign entities brings gains. Public life takes unexpected turns. Partnerships require adaptability.',
    8: 'New investments and risks should be totally avoided. There could be hurdles and hassles. If working as a professional, progress comes only through hard work with a long-term attitude. No shortcut to success. Work environment could be stressful. Health needs careful monitoring.',
    9: 'Fortune through foreign lands and unconventional philosophies. Interest in non-traditional spirituality. International education or teaching. Breaking from traditional beliefs leads to growth.',
    10: 'Career breakthroughs through technology or foreign connections. Unconventional career paths bring success. Corporate leadership through innovation. Sudden rise in public profile. Government technology roles.',
    11: 'Massive gains through networks, technology, and international connections. Wishes manifest through unconventional means. Friendships with foreign or unusual people. Cryptocurrency and technology investments.',
    12: 'Foreign residence or extended international travel. Spiritual experiences in unusual traditions. Expenses through foreign connections. Meditation retreats in exotic locations. Liberation through detachment from convention.',
  },
  KETU: {
    1: 'Spiritual awakening and detachment from ego. Health may fluctuate with unusual symptoms. Past-life connections surface. You become more introspective and philosophical. Simplicity becomes attractive.',
    2: 'Detachment from material accumulation. Family dynamics involve spiritual elements. Speech becomes mystical or cryptic. Income from spiritual or healing work. Dietary changes for health reasons.',
    3: 'Intuitive communications and spiritual writing. Siblings may undergo transformations. Courage through spiritual strength. Interest in ancient languages and texts. Retreats from social communication.',
    4: 'Detachment from material home comforts. Mother\'s spiritual growth. Ancestral property matters arise. Deep meditation practice at home. Connection with homeland through spiritual lens.',
    5: 'Spiritual creativity and past-life connections. Children on unique spiritual paths. Romance has karmic quality. Intuitive abilities sharpen. Interest in ancient education systems.',
    6: 'Overcoming enemies through spiritual means. Unusual health treatments. Service through healing and spiritual counseling. Animals and nature provide healing. Past karma related to service resolves.',
    7: 'Karmic relationships surface for resolution. Marriage has spiritual dimensions. Business partnerships involve spiritual or healing elements. Past-life partners may reconnect.',
    8: 'Deep mystical experiences and kundalini awakening. Interest in death and rebirth philosophies. Hidden knowledge reveals itself. Occult abilities strengthen. Transformation through letting go.',
    9: 'Profound spiritual insights and liberation experiences. Pilgrimage to ancient sacred sites. Father\'s spiritual influence. Mastery of meditation and ancient wisdom. Fortune through spiritual service.',
    10: 'If in a job, dynamic growth but work environment remains stressful. Controversy with superiors possible. Close associates may appear distant. Not much change recommended. Control harsh speech which may create tensions with near and dear ones.',
    11: 'Gains through spiritual networks and communities. Wishes manifest through detachment. Friendships with spiritual seekers. Income from healing or spiritual teaching. Liberation from material desires.',
    12: 'Excellent for spiritual liberation and enlightenment. Foreign ashram or monastery experience. Deep meditation and past-life resolution. Complete spiritual transformation. Ultimate peace through surrender.',
  },
};
