/**
 * PDF Report Generator — creates a professional multi-page Kundli PDF
 * Uses jsPDF for client-side PDF generation
 */
import { jsPDF } from 'jspdf';
import { PLANETS, PLANET_ORDER, RASHIS, DASHA_YEARS } from '../core/constants.js';
import { formatDMS } from '../core/planets.js';
import { generateFullReport } from '../core/interpretations/index.js';
import { formatDashaDate } from '../core/dashas.js';

const GOLD = [218, 165, 32];
const WHITE = [241, 245, 249];
const MUTED = [148, 163, 184];
const DARK = [15, 23, 42];
const SECTION_BG = [30, 41, 59];

/**
 * Generate and download the complete Kundli PDF report
 */
export function downloadKundliPDF(chartData, dashaData, userName) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210, H = 297;
  const M = 18; // margin
  const CW = W - 2 * M; // content width
  let y = 0;

  const report = generateFullReport(chartData, dashaData);
  const name = userName || 'Native';

  // ======== PAGE 1: COVER ========
  drawCoverPage(doc, name, chartData, W, H);

  // ======== PAGE 2: PLANETARY POSITIONS ========
  doc.addPage();
  y = drawHeader(doc, 'Planetary Positions', M, W);
  y = drawPlanetTable(doc, chartData, M, y, CW);

  // ======== PAGE 3: ASCENDANT PROFILE ========
  if (report.ascendant) {
    doc.addPage();
    y = drawHeader(doc, `Your Ascendant — ${report.ascendant.sign}`, M, W);
    y = drawSection(doc, 'Personality', report.ascendant.personality, M, y, CW);
    y = drawSection(doc, 'Appearance', report.ascendant.appearance, M, y, CW);
    y = drawSection(doc, 'Nature', report.ascendant.nature, M, y, CW);
    y = drawSection(doc, 'Career Inclinations', report.ascendant.career, M, y, CW);
    y = drawSection(doc, 'Health Profile', report.ascendant.health, M, y, CW);
    y = drawSection(doc, 'Relationships', report.ascendant.relationships, M, y, CW);
  }

  // ======== PAGE 4: NAKSHATRA PHAL ========
  if (report.nakshatra) {
    doc.addPage();
    y = drawHeader(doc, `Nakshatra Phal — ${report.nakshatra.nakshatra}`, M, W);
    y = drawSubtitle(doc, `Deity: ${report.nakshatra.deity}  |  Symbol: ${report.nakshatra.symbol}  |  Moon in ${report.nakshatra.moonSign}  |  Pada ${report.nakshatra.pada}`, M, y, CW);
    y = drawSection(doc, 'Personality', report.nakshatra.personality, M, y, CW);
    y = drawSection(doc, 'Key Traits', report.nakshatra.traits, M, y, CW);
    y = drawSection(doc, 'Life Path', report.nakshatra.life, M, y, CW);
  }

  // ======== PAGES 5-6: LIFE PREDICTIONS ========
  if (report.lifePredictions) {
    doc.addPage();
    y = drawHeader(doc, `Life Predictions — ${report.lifePredictions.moonSign} Moon`, M, W);
    for (const section of report.lifePredictions.sections) {
      if (y > 245) { doc.addPage(); y = drawHeader(doc, 'Life Predictions (continued)', M, W); }
      y = drawSection(doc, section.title, section.text, M, y, CW);
    }
  }

  // ======== PAGES: DASHA PREDICTIONS ========
  if (report.dashaPredictions && report.dashaPredictions.length > 0) {
    doc.addPage();
    y = drawHeader(doc, 'Vimshottari Mahadasha Phal', M, W);
    for (const dp of report.dashaPredictions) {
      if (y > 230) { doc.addPage(); y = drawHeader(doc, 'Mahadasha Phal (continued)', M, W); }
      const dateRange = `${formatDashaDate(dp.startDate)} – ${formatDashaDate(dp.endDate)}`;
      const subTitle = `${dp.lordName} in ${dp.sign} in your ${ordinal(dp.house)} house`;
      y = drawDashaPrediction(doc, `${dp.lordName} Mahadasha (${dateRange})`, subTitle, dp.prediction, dp.isActive, M, y, CW);
    }
  }

  // ======== PAGE: PLANETARY INSIGHTS ========
  if (report.planetaryInsights && report.planetaryInsights.length > 0) {
    doc.addPage();
    y = drawHeader(doc, 'Planetary Insights & Dignities', M, W);
    for (const insight of report.planetaryInsights) {
      if (y > 245) { doc.addPage(); y = drawHeader(doc, 'Planetary Insights (continued)', M, W); }
      const noteText = insight.notes.join(' ');
      y = drawSection(doc, `${insight.planet} (${insight.sanskrit}) — House ${insight.house}, ${insight.sign}`, noteText, M, y, CW);
    }
  }

  // ======== FOOTER ON ALL PAGES ========
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text('Generated by Jyotish Vedic — Accurate Indian Astrology', W / 2, H - 8, { align: 'center' });
    doc.text(`Page ${i} of ${totalPages}`, W - M, H - 8, { align: 'right' });
  }

  // Download
  const fileName = `${name.replace(/\s+/g, '_')}_Kundli_Report.pdf`;
  doc.save(fileName);
}

// ============ DRAWING HELPERS ============

function drawCoverPage(doc, name, chartData, W, H) {
  // Background
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, H, 'F');

  // Decorative border
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.8);
  doc.rect(12, 12, W - 24, H - 24);
  doc.setLineWidth(0.3);
  doc.rect(15, 15, W - 30, H - 30);

  // Om symbol
  doc.setFontSize(48);
  doc.setTextColor(...GOLD);
  doc.text('\u0950', W / 2, 70, { align: 'center' });

  // Title
  doc.setFontSize(32);
  doc.setTextColor(...GOLD);
  doc.text('Jyotish Vedic', W / 2, 95, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(...MUTED);
  doc.text('ACCURATE INDIAN ASTROLOGY', W / 2, 105, { align: 'center' });

  // Divider
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.line(60, 115, W - 60, 115);

  // Name
  doc.setFontSize(22);
  doc.setTextColor(...WHITE);
  doc.text(name, W / 2, 135, { align: 'center' });

  // Birth details
  const bd = chartData.birthData;
  const dateStr = bd.date.toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  const asc = chartData.ascendant;

  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  const details = [
    `Date of Birth: ${dateStr}`,
    `Latitude: ${bd.latitude.toFixed(4)}°  |  Longitude: ${bd.longitude.toFixed(4)}°`,
    `Ascendant: ${asc.rashiName} (${asc.rashiSanskrit}) ${asc.dms.display}`,
    `Moon Sign: ${chartData.planets.MOON.rashiName} (${chartData.planets.MOON.rashiSanskrit})`,
    `Moon Nakshatra: ${chartData.planets.MOON.nakshatra.name} — Pada ${chartData.planets.MOON.nakshatra.pada}`,
    `Ayanamsa (Lahiri): ${chartData.ayanamsa.toFixed(4)}°`,
  ];
  let dy = 155;
  for (const line of details) {
    doc.text(line, W / 2, dy, { align: 'center' });
    dy += 8;
  }

  // Bottom decorative line
  doc.setDrawColor(...GOLD);
  doc.line(60, H - 40, W - 60, H - 40);
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text('This report is generated using NASA-grade astronomical calculations', W / 2, H - 30, { align: 'center' });
}

function drawHeader(doc, title, M, W) {
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, 297, 'F');

  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.line(M, 18, W - M, 18);

  doc.setFontSize(16);
  doc.setTextColor(...GOLD);
  doc.text(`|| ${title} ||`, W / 2, 14, { align: 'center' });

  return 28;
}

function drawSubtitle(doc, text, M, y, CW) {
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  doc.text(text, M, y);
  return y + 8;
}

function drawSection(doc, title, text, M, y, CW) {
  if (!text) return y;

  doc.setFontSize(11);
  doc.setTextColor(...GOLD);
  doc.text(title, M, y);
  y += 6;

  doc.setFontSize(9.5);
  doc.setTextColor(...WHITE);
  const lines = doc.splitTextToSize(text, CW);
  doc.text(lines, M, y);
  y += lines.length * 4.2 + 6;

  return y;
}

function drawDashaPrediction(doc, title, subtitle, text, isActive, M, y, CW) {
  if (isActive) {
    doc.setFillColor(218, 165, 32, 15);
    doc.roundedRect(M - 2, y - 4, CW + 4, 8, 1, 1, 'F');
  }

  doc.setFontSize(11);
  doc.setTextColor(isActive ? 34 : 218, isActive ? 197 : 165, isActive ? 94 : 32);
  doc.text(title + (isActive ? '  [CURRENT]' : ''), M, y);
  y += 5;

  doc.setFontSize(8.5);
  doc.setTextColor(...MUTED);
  doc.text(subtitle, M, y);
  y += 5;

  if (text) {
    doc.setFontSize(9.5);
    doc.setTextColor(...WHITE);
    const lines = doc.splitTextToSize(text, CW);
    doc.text(lines, M, y);
    y += lines.length * 4.2 + 4;
  }
  return y + 3;
}

function drawPlanetTable(doc, chartData, M, y, CW) {
  const colW = [28, 30, 22, 16, 36, 24, 22];
  const headers = ['Planet', 'Rashi', 'Degree', 'House', 'Nakshatra', 'Nak Lord', 'Dignity'];

  // Header row
  doc.setFillColor(...SECTION_BG);
  doc.rect(M, y - 4, CW, 7, 'F');
  doc.setFontSize(8.5);
  doc.setTextColor(...GOLD);
  let x = M + 2;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x, y);
    x += colW[i];
  }
  y += 7;

  // Data rows
  doc.setFontSize(8.5);
  for (const key of PLANET_ORDER) {
    const p = chartData.planets[key];
    x = M + 2;
    doc.setTextColor(...WHITE);
    doc.text(`${p.name} (${p.sanskrit})`, x, y); x += colW[0];
    doc.text(`${p.rashiName}`, x, y); x += colW[1];
    doc.text(p.dms.display, x, y); x += colW[2];
    doc.text(`${p.house}`, x, y); x += colW[3];
    doc.text(`${p.nakshatra.name} P${p.nakshatra.pada}`, x, y); x += colW[4];
    const lordName = PLANETS[p.nakshatra.lord]?.name || p.nakshatra.lord;
    doc.text(lordName, x, y); x += colW[5];

    doc.setTextColor(
      p.dignity.status === 'exalted' ? 34 : p.dignity.status === 'debilitated' ? 239 : 148,
      p.dignity.status === 'exalted' ? 197 : p.dignity.status === 'debilitated' ? 68 : 163,
      p.dignity.status === 'exalted' ? 94 : p.dignity.status === 'debilitated' ? 68 : 184,
    );
    let dignityStr = p.dignity.label;
    if (p.retrograde && key !== 'RAHU' && key !== 'KETU') dignityStr += ' (R)';
    doc.text(dignityStr, x, y);

    y += 6;
    doc.setDrawColor(50, 60, 80);
    doc.setLineWidth(0.1);
    doc.line(M, y - 2, M + CW, y - 2);
  }

  // Ascendant row
  const asc = chartData.ascendant;
  doc.setTextColor(...GOLD);
  doc.text(`Ascendant: ${asc.rashiName} (${asc.rashiSanskrit}) ${asc.dms.display} — Nakshatra: ${asc.nakshatra.name} Pada ${asc.nakshatra.pada}`, M + 2, y + 4);
  y += 12;

  return y;
}

function ordinal(n) {
  const s = ['th','st','nd','rd'];
  const v = n % 100;
  return n + (s[(v-20)%10] || s[v] || s[0]);
}
